version: "3"

services:
  node:
    image: node:17.0.0-alpine
    user: node
    tty: true
    stdin_open: true
    entrypoint: node
    working_dir: /home/node
    ports:
      - 8000:8000
    volumes:
      - .:/home/node